name: CI-ariana

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE

      - name: Test
        run: python -m unittest discover -v . "test*.py"
